### ISSUE TITLE
autocomplete results don't scroll on iOS 7 / iphone 5s, safari and chrome

### ISSUE THREAD

**Issue by hickerm** [varvet/tiny-autocomplete#19]
Hello,

Testing via browserstack, autocomplete results don't seem to scroll for:

iPhone 5S
iOS 7
Both Safari and Chrome

https://imgur.com/a/aQAGN
https://imgur.com/a/shi6Z

When trying to scroll the autocomplete results, the underlying page gets scrolled.

When stepping up to the next level in browserstack:

iPhone 6
iOS 8
Both Safari and Chrome

https://imgur.com/a/v1aro
https://imgur.com/a/BFpf0

The autocomplete results seem to scroll OK.

I did add the following rule to the following selector in the tiny-autocomplete.css:

`.autocomplete .autocomplete-list {
    -webkit-overflow-scrolling: touch;
}`

To provide the visual scroll indicator in the autocomplete results, but it only displays when you're actually scrolling the list on mobile. 

You might want to think about adding this to your css?

Android seems to fair better, I chose a random old'ish type of device/OS:

Nexus 5 Android 4.4
https://imgur.com/a/Wu3Jt

And it scrolls OK.

A couple things that I think would be extremely nice would be:

- If you actually had a demo page of tiny-autocomplete that was served up like you mention in your README file so people can easily go test it
- If you actually listed baseline mobile browser support (along with any noted limitations), instead of just saying "Working on tablets and mobile devices"

"Working" is all relative, I suppose, but for some, the iPhone 5S non-scrolling may be a show stopper and it'd probably be nice if they knew about that before they get to far on a project.

**Comment by johanhalse** [comment]
Great detective work and a good write-up! ⭐️

I added your fix to the default CSS and as far as I can tell it's working well. The reason I haven't updated or merged many features to tiny-autocomplete for a good long while is the lack of tests which, incidentally, is also why I haven't specified a baseline device support. An automated pipeline for that is a lot of work and in a way this plugin is already "done", the sites where we're using it are ticking along. If someone were to help out with automated frontend tests in different devices it'd be a different story 😉

As for the demo page, yeah. The main reason I haven't done that is because tiny-autocomplete works best with server-provided data and that requires a backend of some sort, to filter the query and showcase stuff like the server provided template strings. The html files in the repo that use local data can be double-clicked if you want to get a feel for them, but the real value of an online demo would be to showcase the plugin so people can get a feel for whether they want to use it or not. If I find a few hours hidden behind the couch I could maybe put the local demos on S3 as a first step.
