### ISSUE TITLE
Multiple value

### ISSUE THREAD

**Issue by Perfect7M** [varvet/tiny-autocomplete#9]
Can you add function which get multiple values like one on jqueryui? eg value, vale 2, and here can write extra values

**Comment by johanhalse** [comment]
I'm not sure it fits into the "small and fast" ethos of Tiny Autocomplete but it's pretty easy to monkeypatch the onKeyUp function to only request the stuff after the user's last comma:
https://github.com/varvet/tiny-autocomplete/blob/master/src/tiny-autocomplete-0.4.1.js#L499

Where you have
```this.request( this.field.val() );```

you could do something like this instead:
```this.request( this.field.val() ).split(',').pop();```

That would give you the search results you're after. The hard part is figuring out what to do with the results when they come back - instead of just setting the val() of your text field you might have to wipe everything after that last comma and replace with whatever the server returned to you. But it's not rocket surgery either :smiley:

Let me know if that helps! If you can extract something small and robust from your patch that you feel can be put behind an option, open a pull request and we'll consider merging it. But we won't be adding this function ourselves.

**Comment by Perfect7M** [comment]
Yes its working but better solution is this from jquery ui autocomplete this.request( this.field.val().split(/,\s*/).pop() ); where input when we typing can have white space :) is this more flexible and pretty
